### PR TITLE
[WIP] Add Default Definitions

### PR DESCRIPTION
**Pull request by mattapperson**
Adding support for built-ins per ticket #18 

NOT READY TO MERGE

### CODE REVIEW

**Comment by mattapperson** [comment]
Stubbed out the same tests that calabash had as a default

**Comment by eridem** [comment]
Hi Matt, 

I am not really agree with the built ins. This look like you are creating a way to write the specifications within the framework. Giving less flexibility to the final user to use their own syntax.

Each project can create their own "built ins" if they decide so.

**Comment by eridem** [comment]
Closed due discontinued conversation.

**Comment by mattapperson** [comment]
Sorry, I missed your mention. This would not remove each projects ability to use their own syntax, just lets it work out of the box and let devs expand on the basic included features

**Pull request closed without merging**
